FROM python:3.11-slim

# working directory
WORKDIR /app

# copy requirements first (cache optimization)
COPY requirements.txt .

# install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# copy project
COPY . .

# expose fastapi port
EXPOSE 8000

# run server
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]