/**
 * Contract Clause Tracker API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContractDashboard { 
    id: number;
    name: string;
    sentence_count: number;
    labeled_count: number;
    created_at: string;
    status: string;
}

