/**
 * Contract Clause Tracker API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SentenceWithLabel { 
    id: number;
    text: string;
    order: number;
    clause_type_id?: number | null;
    clause_type_name?: string | null;
}

